# Generated by Django 5.1.7 on 2025-04-17 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platform_logos/')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_endpoint', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('ideal_answer', models.TextField(blank=True, null=True)),
                ('tips', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('session_notes', models.TextField(blank=True, null=True)),
                ('session_feedback', models.TextField(blank=True, null=True)),
                ('session_recording', models.FileField(blank=True, null=True, upload_to='interview_recordings/')),
                ('session_transcript', models.TextField(blank=True, null=True)),
                ('session_score', models.FloatField(blank=True, null=True)),
                ('external_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='interview_coaching.coachingplatform')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='profiles.profile')),
                ('interview_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='interview_coaching.interviewtype')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('response_audio', models.FileField(blank=True, null=True, upload_to='interview_responses/')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('response_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interview_coaching.interviewquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interview_coaching.interviewsession')),
            ],
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='interview_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview_coaching.interviewtype'),
        ),
        migrations.CreateModel(
            name='SessionFeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('improvement_suggestion', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='interview_coaching.feedbackcategory')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='interview_coaching.interviewsession')),
            ],
        ),
    ]
